// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";

import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read directly, NOT prisma's env() — env() throws at config load when the
    // var is missing, which breaks `prisma generate` in CI and the Docker build
    // (generate reads the schema and never connects). Commands that DO need a
    // connection (migrate dev) still fail clearly when it's empty. Runtime
    // migrations run through the server bundle, not this config.
    url: process.env.DATABASE_URL ?? "",
  },
});
