#!/bin/sh
# `open-panel install` — writes docker-compose.yml + .env into /output.
#
#   docker run --rm -v "$PWD:/output" open-panel:1.1.0 install
#
# Deliberately does NOT run docker itself: that would need the docker CLI baked
# into every container and a mounted docker.sock (root-equivalent on the host).
set -e

OUT=/output

if [ ! -d "$OUT" ]; then
  echo "error: nothing mounted at /output." >&2
  echo "  docker run --rm -v \"\$PWD:/output\" open-panel:1.1.0 install" >&2
  exit 1
fi

# 32 random bytes, base64 — matches what the app expects for both keys.
gen_secret() {
  bun -e 'console.log(Buffer.from(crypto.getRandomValues(new Uint8Array(32))).toString("base64"))'
}

if [ -f "$OUT/.env" ]; then
  # Never regenerate secrets over an existing install: OPENPANEL_ENC_KEY
  # decrypts stored SSH credentials, so a new key silently orphans every
  # registered server.
  echo "  kept    .env (already exists — secrets left untouched)"
else
  cat > "$OUT/.env" <<EOF
# Generated by \`open-panel install\`. Keep this file secret and back it up.
#
# OPENPANEL_ENC_KEY decrypts the SSH credentials stored in the database —
# losing or changing it orphans every registered server.

# Image to run. Retag/push and change this to deploy your own build.
IMAGE=${IMAGE:-open-panel:1.1.0}

# Public URLs. Change both when serving on a real domain, e.g.
#   PUBLIC_URL=https://panel.example.com
#   PUBLIC_WS_URL=wss://panel.example.com:3001/api/terminal
# The browser connects to PUBLIC_WS_URL directly, so it must be reachable
# from the browser — not a Docker-internal hostname.
PUBLIC_URL=http://localhost:3000
PUBLIC_WS_URL=ws://localhost:3001/api/terminal

# Database — bring your own reachable Postgres (managed or self-hosted). This
# stack does not run one. Fill this in before \`docker compose up\`.
DATABASE_URL=${DATABASE_URL:-postgresql://user:password@host:5432/open_panel}

# Session signing + terminal-ticket HMAC.
BETTER_AUTH_SECRET=$(gen_secret)
# AES-256-GCM key for SSH credentials at rest.
OPENPANEL_ENC_KEY=$(gen_secret)
EOF
  chmod 600 "$OUT/.env"
  echo "  wrote   .env (secrets generated)"
fi

if [ -f "$OUT/docker-compose.yml" ]; then
  echo "  skipped docker-compose.yml (already exists — delete it to regenerate)"
else
  cp /app/install/docker-compose.yml "$OUT/docker-compose.yml"
  echo "  wrote   docker-compose.yml"
fi

cat <<EOF

Next:

  1. Set DATABASE_URL in .env to your Postgres (this stack does not run one).
  2. docker compose up -d
  3. docker compose run --rm server seed    # create the first admin user

Then open http://localhost:3000 and sign in as admin@openpanel.local / admin12345
(change the password immediately, or set SEED_EMAIL / SEED_PASSWORD before seeding).
EOF
